VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "PnLArchive"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = False
Option Explicit

Private m_oPnL As Collection
Private m_dDate As Date

'
' read the file from disk
' save PnL for each book and each position
'

Sub addPnLCube()


End Sub
